
# ERROR, WARNING, or INFO
verbosity: WARNING
# log-file: log.json
# fail-if-warnings: false
# dump-args: false
# ignore-args: false
# trace: false

from: markdown-smart

metadata:
  title: A Proper Title
  rights: Â© Copyright 2026, All rights reserved
  lang: en-US
  author: Jane Doe
  contact: books@example.com | 888-555-1234
  dedication: Dedicated to our dogs
